# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transition.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10transition.proto\x12\x10transition.proto\"\xbb\x01\n\nTransition\x12\r\n\x05state\x18\x01 \x01(\x0c\x12\x0e\n\x06\x61\x63tion\x18\x02 \x01(\r\x12\x0e\n\x06reward\x18\x03 \x01(\x02\x12\x12\n\nnext_state\x18\x04 \x01(\x0c\x12\x0c\n\x04\x64one\x18\x05 \x01(\x08\x12\x13\n\x0bstate_shape\x18\x06 \x03(\x05\x12\x13\n\x0bstate_dtype\x18\x07 \x01(\t\x12\x18\n\x10next_state_shape\x18\x08 \x03(\x05\x12\x18\n\x10next_state_dtype\x18\t \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transition_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TRANSITION']._serialized_start=39
  _globals['_TRANSITION']._serialized_end=226
# @@protoc_insertion_point(module_scope)
